# -*- coding: utf-8 -*-
"""hw1_binary_hex_converterhw1_binary_hex_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1691SpBq5KBV3iBQJ7pjfVWcsgT6Fkoe4
"""

def decimal_to_binary(n):
    bits = [0] * 8  # 8 個變數代表 2 的 0 次方到 7 次方
    for i in range(8):
        bits[7 - i] = (n >> i) & 1  # 依序填入每一位元
    return "".join(map(str, bits))

def decimal_to_hex(n):
    high = n // 16  # 取前 4 位
    low = n % 16  # 取後 4 位
    hex_chars = "0123456789ABCDEF"
    return hex_chars[high] + hex_chars[low]

def main():
    while True:
        try:
            decimal = int(input("請輸入 0-255 之間的數字: "))
            if 0 <= decimal <= 255:
                binary_result = decimal_to_binary(decimal)
                hex_result = decimal_to_hex(decimal)
                print(f"二進位: {binary_result}")
                print(f"十六進位: {hex_result}")
            else:
                print("請輸入範圍內的數字！")
        except ValueError:
            print("請輸入有效的整數！")

if __name__ == "__main__":
    main()